---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.

- name: restart ntp
  service: name=ntpd state=restarted

- name: restart iptables
  service: name=iptables state=restarted
