---
# This playbook handles the removal of a webserver from the pool.

- name: Remove the code from server
  command: rm -rf /var/www/html/*

- name: Remove server from LB
  lineinfile: dest=/etc/haproxy/haproxy.cfg state=absent regexp="${ansible_hostname}" 
  delegate_to: $item
  with_items: ${groups.lbservers}
  register: last_run

- name: disable the server in haproxy
  shell: echo "disable server myapplb/${ansible_hostname}" | socat stdio /var/lib/haproxy/stats
  delegate_to: $item
  with_items: ${groups.lbservers}

- name: Remove the httpd package
  yum: name=httpd state=absent



 
