---
- name: Add Amazon AWS Credentials
  tower_credential:  
    name: AWS Sales API Key
    description:  AWS API Key for Sales
    organization: Default
    #config_file: ~/tower_cli.cfg
    kind: aws
    username: "{{ aws_access_key }}"
    password: "{{ aws_secret_key }}"
    state: present

- name: Add Amazon SSH keys
  tower_credential:
    name: AWS SSH Key
    description:  AWS SSH Machine Key
    organization: Default
    #config_file: ~/tower_cli.cfg
    kind: ssh
    username: "{{ aws_ssh_user }}"
    ssh_key_data: ~/lrich-key.pem
    state: present

- name: Add AWS Windows Password
  tower_credential:
    name: AWS Windows Password
    description: Windows Password for AWS machines
    organization: Default
    #config_file: ~/tower_cli.cfg
    kind: ssh
    state: present
    username: Administrator
    password:  "{{ aws_windows_password }}"
    vault_password: "{{ vault_password }}"

- name: Add AWS Windows Password
  tower_credential:
    name: AWS Windows Password
    description: Windows Password for AWS machines
    organization: Default
    #config_file: ~/tower_cli.cfg
    kind: ssh
    state: present
    username: Administrator
    password:  "{{ aws_windows_password }}"
    vault_password: "{{ vault_password }}"

- name: Add Network Credentials
  tower_credential:
    name: Network Credentials
    description: Credentials for Network Devices
    organization: Default
    #config_file: ~/tower_cli.cfg
    kind: net
    state: present
    username: ec2-user
    ssh_key_data: ~/lrich-key.pem


#- name: Add Tower Password
#  tower_credential:
#    name: Tower Password
#    description: Password for Ansible Tower
#    organization: Default
#    config_file: ~/tower_cli.cfg
#    kind: ssh
#    ssh_key_data: ~/.ssh/id_rsa
#    state: present
#    username: root
#    password:  "{{ vault_password }}"    
