---
# This Playbook adds  a webserver into the the web cluster

- hosts: webservers
  user: root
  serial: 1
  tasks:
   - include: ../roles/web/tasks/install_httpd.yml
   - include: ../roles/web/tasks/copy_code.yml
   - include: ../roles/web/tasks/add_to_lb.yml
