---
# This role installs HAProxy and configures it.

- name: Download and install haproxy
  yum:
    name: haproxy
    state: present

- name: Configure the haproxy cnf file with hosts
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Start the haproxy service
  service:
    name: haproxy
    state: started
    enabled: true
