---
# These tasks install http and the php modules.

- name: Install http and php etc
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - httpd
      - php
      - php-mysql
      - git
      - libsemanage-python
      - libselinux-python

- name: Insert iptables rule for httpd
  ansible.builtin.lineinfile:
    dest: /etc/sysconfig/iptables
    create: true
    state: present
    regexp: "{{ httpd_port }}"
    insertafter: "^:OUTPUT "
    line: -A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT
  notify: restart iptables

- name: Http service state
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Configure SELinux to allow httpd to connect to remote database
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true
  when: sestatus.rc != 0
