---
# These tasks install http and the php modules.

- name: Install httpd and php
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - php
    - php-mysql

- name: Install web role specific dependencies
  ansible.builtin.yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - git

- name: Start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Insert firewalld rule for httpd
  ansible.posix.firewalld:
    port: "{{ httpd_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: Http service state
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Configure SELinux to allow httpd to connect to remote database
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true

