---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  ansible.builtin.yum:
    name: ntp
    state: present
  tags: ntp

- name: Configure ntp file
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart_ntp

- name: Start the ntp service
  ansible.builtin.service:
    name: ntpd
    state: started
    enabled: true
  tags: ntp

- name: Test to see if selinux is running
  ansible.builtin.command: getenforce
  register: sestatus
  changed_when: false
